apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: {{ .Release.Name }}
spec:
  provider: istio

  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}

  service:
    port: 80
    gateways:
      - canary-gateway
    hosts:
      - "*"

  analysis:
    interval: 30s
    threshold: 5
    maxWeight: 50
    stepWeight: 10

    metrics:
      - name: request-success-rate
        thresholdRange:
          min: 99
        interval: 30s

      - name: request-duration
        thresholdRange:
          max: 500
        interval: 30s

