apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  provider: istio
  replicas: {{ .Values.replicaCount }}

  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}

  service:
    port: 80
    targetPort: 80
    gateways:
      - canary-gateway
    hosts:
      - "*"

  analysis:
    interval: 1m
    threshold: 3
    maxWeight: 50
    stepWeight: 10

    metrics:
      - name: request-success-rate
        interval: 1m
        thresholdRange:
          min: 99

      - name: request-duration
        interval: 1m
        thresholdRange:
          max: 500

  progressDeadlineSeconds: 60

