apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-stable
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
      version: stable
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
        version: stable
    spec:
      containers:
      - name: app
        image: "{{ .Values.image.repository }}:{{ .Values.stable.tag }}"
        ports:
        - containerPort: 80
