apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
      version: canary
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
        version: canary
    spec:
      containers:
      - name: app
        image: "{{ .Values.image.repository }}:{{ .Values.canary.tag }}"
        ports:
        - containerPort: 80
