apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ .Release.Name }}
spec:
  host: {{ .Release.Name }}
  subsets:
  - name: stable
    labels:
      version: stable
  - name: canary
    labels:
      version: canary
