apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}
spec:
  hosts:
  - "*"
  gateways:
  - canary-gateway
  http:
  - route:
    - destination:
        host: {{ .Release.Name }}
        subset: stable
      weight: 90
    - destination:
        host: {{ .Release.Name }}
        subset: canary
      weight: 10
