app:
  name: canary-app

image:
  repository: caominhquang1604/canary-app

stable:
  version: stable
  tag: "87ade2a"        # tag cố định (hoặc commit đã promote)

canary:
  version: canary
  tag: "512e33c"        # CI sẽ update chỗ này
